name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the package
      uses: actions/checkout@v2
    - name: Install software
      run: |
        sudo apt -y update
        sudo apt -y install plantuml      
        python -m pip install --upgrade pip
        make user
    - name: Install dependencies for development/documentation
      run: |
        pip install -r requirements_dev.txt
    - name: Generate the documentation for each tag
      run: |
        make doc    
    - name: Deploy documentation to GH Pages 🚀
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: docs/build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
