name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the package
      uses: actions/checkout@v2
    - name: Install software
      run: |
        sudo apt -y update
        sudo apt -y install plantuml      
        python -m pip install --upgrade pip
        make user
    - name: Install dependencies for development/documentation
      run: |
        pip install -r requirements_dev.txt
    - name: Generate and deploy documentation for each tag to GH Pages 🚀
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make doc
        cd docs/build/html && \
        git config --global init.defaultBranch master        
        git init && \
        git add . && \
        git -c user.name='GitHub Actions' -c user.email='actions@github.com' \
        commit -m "Deploy Sphinx documentation" && \
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git && \
        git push gh-pages        
        
