name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the package
      uses: actions/checkout@v2
    - name: Install software
      run: |
        sudo apt -y update
        sudo apt -y install plantuml
        python -m pip install --upgrade pip
        make user
    - name: Install dependencies for development/documentation
      run: |
        pip install -r requirements_dev.txt
    - name: Generate the documentation for each tag
      run: |
        git tag -l
        make doc
    - name: Deploy documentation to GH Pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
